config/routes.rb
Rails.application.routes.draw do
  get 'relationships/follow_user'

  get 'relationships/unfollow_user'
  post ':user_id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'browse', to: 'posts#browse', as: :browse_posts

  devise_for :users
  root 'posts#index'
  resources :posts do
  	resources :comments
  	resources :upvotes, only: :create
  	resources :downvotes, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	validates :description, :user_id, :post_id, presence: true
	delegate :name, to: :user, prefix: true
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
	belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
	mount_uploader :photo, PhotoUploader
	def user_photo
		user.photo
	end

	def user_name
		user.name
	end
	validates :photo, :description, :user_id, presence: true
	acts_as_votable
	delegate :photo, :name, to: :user, prefix: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :photo, PhotoUploader
  has_many :posts
  has_many :comments
  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following
  acts_as_voter

  def follow(user_id)  
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name, :photo) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :photo) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: :create
	before_action :is_owner?, only: :destroy
	def create
		@post = Post.find(params[:post_id])
 	    @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
 	   
		if @comment.valid?
			redirect_to root_path
		else
			flash[:alert] = "Invalid attributes."
			redirect_to root_path
    	end
	end

	def new
		@comment = Comment.new
	end

	def index
		@comments = Comment.all
	end

	def destroy
		@comment=Comment.find(params[:id])
		@comment.destroy
		redirect_to root_path
	end

	def is_owner?
		@comment = Comment.find(params[:id])
		if @comment.user != current_user
			redirect_to root_path
		end
	end

	private

	def comment_params
	  params.require(:comment).permit(:user_id, :post_id, :description)
	end
end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
	before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @post.downvote_from current_user
    respond_to do |format|
	  format.html { redirect_to posts_path }
	  format.js {}
	end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	before_action :is_owner?, only: [:edit, :update, :delete]
	def new
		@post = Post.new
	end

	 def create
  	  @post = current_user.posts.create(post_params)
        if @post.valid?
        	redirect_to root_path
        else
        render :new, status: :unprocessable_entity
        end
    end

    def show
        @posts = Post.find(params[:id])
    end

    def index
      if user_signed_in?
        @posts = Post.all.order('created_at DESC').includes(:user, comments: :user).paginate(page: params[:page], per_page: 2)
      else
        @posts = Post.all.order('created_at DESC').includes(:user, comments: :user).paginate(page: params[:page])
      end
    end

    def edit
    	   @post = Post.find(params[:id])
    end

    def update
    	  @post = Post.find(params[:id])
    	  @post.update(post_params)
    	  if @post.valid?
      	 redirect_to root_path
    	  else
        	render :edit, status: :unprocessable_entity
        end
	  end
	def destroy
  		@post = Post.find(params[:id])
  		@post.destroy
  		redirect_to root_path
	end
  def browse
      @posts = Post.all.order('created_at DESC').page params[:page]
  end
  
    private
		def is_owner?
		  redirect_to root_path if Post.find(params[:id]).user != current_user
		end
		def post_params
			params.require(:post).permit(:user_id, :photo, :description)
		end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def follow_user
		@user = User.find_by! id: params[:user_id]
		if current_user.follow @user.id
			respond_to do |format|
				format.js { redirect_to user_path(@user.id) }
			end
		end
	end

	def unfollow_user
		@user = User.find_by! id: params[:user_id]
		if current_user.unfollow @user.id
			respond_to do |format|
				format.js { redirect_to user_path(@user.id) }
			end
		end
	end
 end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
  		@post.liked_by current_user
  		respond_to do |format|
			format.html { redirect_to posts_path }
			format.js {}
		end

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/downvotes/create.js.erb
$('#likes_container_<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html>
  <head>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <%= favicon_link_tag 'img1.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Share Your Photos Online - Instapost</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fullwidth">
  <nav class="navbar">
      <div class="container-fluid">
        <div class='col-md-4'>
          <div class="pull-left brand no-dec">
             <%= link_to root_path do %><span i class="fa fa-instagram" style="font-size:36px"></i><% end %>
             <span hr class="vertical">
             <%= link_to 'Instagram', root_path%></span>
          </div>
        </div>

        <div class='col-md-3'>
          <!-- search box -->
          <div class="input-group stylish-input-group">
              <input type="text" class="form-control"  placeholder="Search" >
                <span class="input-group-addon">
                    <button type="submit">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>  
                </span>
            </div>
        </div>

        <div class='col-md-5'>
          <ul class="nav nav-tabs pull-right no-dec">
            <% if user_signed_in? %>
              <li><%= link_to browse_posts_path do %>
                <i class="fa fa-history" style="font-size:26px"></i><% end %>
              </li>
              <li><%= link_to edit_user_registration_path do %>
                  <i class="fa fa-cog", style="font-size:26px"></i><% end %>
              </li> 
              <li><%= link_to new_post_path do %>
                <i class="fa fa-heart-o", style="font-size:26px"></i><% end %>
              </li>
              <li><%= link_to user_path(current_user.id) do %>
                <i class="fa fa-user-o", style="font-size:26px"></i><% end %>
              </li>

            <% else %>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li><%= link_to 'Log In', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
  </nav>
    </div>

  <%= yield %>
  </body>
</html>

app/views/posts/_likes.html.erb
<% if user_signed_in? %>
  <span class="post_like">
    <% if current_user.voted_up_on? post %>
      <%= link_to '<i class="fa fa-heart" aria-hidden="true"></i>'.html_safe, post_downvotes_path(post.id), method: :post, remote: true %> 
    <% else %>
      <%= link_to '<i class="fa fa-heart-o" aria-hidden="true"></i>'.html_safe, post_upvotes_path(post.id), method: :post, remote: true %>
    <% end %>
    <%= pluralize post.get_likes.size, "like" %>
  </span>
<% else %>
  <span class="post_like">
    <i class="fa fa-heart-o" aria-hidden="true"></i><%= pluralize post.get_likes.size, "like" %>
  </span>
<% end %>

app/views/posts/_post.html.erb
  <div class="panel panel-default panel-design" >
    <div class="post_box">
      <div class="post_header">
        <%= image_tag post.user_photo, class: 'prof_pic_small' %>
        <%= link_to post.user_name, user_path(post.user_id), class: 'new-dec'%>
        <span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago</span>
      </div>
      
      <%= link_to post_path(post.id) do %>
        <center><%= image_tag post.photo, class: 'photo' %></center>
      <% end %> 
      
      <div class="post_body">
        <%= link_to post.user.name, user_path(post.user_id) %> <%= post.description %>
      </div>
      <div class="post_comments">
        <% post.comments.each do |comment| %>
          <%= link_to comment.user_name,  user_path(comment.user_id) %> <%= comment.description %>
        <% end %>
        <hr>
        <span id="likes_container_<%= post.id %>">
          <%= render partial: 'likes', locals: {post: post} %>
        </span>
        <% if user_signed_in? %>
          <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do |f| %>
            <%= f.input :description, label: 'Comment', placeholder: 'Add a comment...' %>
            <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/posts/browse.html.erb
  <div id="posts" _post>
<% @posts.each do |post| %>
  <%= render partial: 'post', locals: {post: post} %>
<% end %>
</div>
<%= will_paginate @posts %>
  

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>
<%= simple_form_for @post do |f| %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.submit 'Update', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="panel panel-default panel-design">
    <div class="post_box">
      <div class="post_header">
        <%= image_tag post.user.photo, class: 'prof_pic_small' %>
        <%= link_to post.user.name, user_path(post.user_id), class: 'new-dec'%>
        <span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago</span>
      </div>
      <center><%= image_tag post.photo, class: 'photo' %></center>
      <div class="post_body">
        <%= link_to post.user.name, user_path(post.user_id) %> <%= post.description %>
      </div>
      <div class="post_comments">
        <% post.comments.each do |comment| %>
          <%= link_to comment.user.name,  user_path(comment.user_id) %> <%= comment.description %>
        <% end %>
        <hr>
        <span id="likes_container_<%= post.id %>">
          <%= render partial: 'likes', locals: {post: post} %>
        </span>
        <% if user_signed_in? %>
          <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do |f| %>
            <%= f.input :description, label: 'Comment', placeholder: 'Add a comment...' %>
            <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

  

app/views/posts/index.js.erb
$('#posts').append('<%= escape_javascript render(@posts) %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@posts) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.submit 'Post' , class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/show.html.erb
<div class="panel panel-default panel-design" >
    <div class="post_box">
      <div class="post_header">
        <%= image_tag @posts.user.photo, class: 'prof_pic_small' %>
        <%= link_to @posts.user.name, user_path(@posts.user_id), class: 'new-dec'%>
        <span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, @posts.created_at) %> ago</span>
      </div>
    
      <%= link_to post_path(@posts.id) do %>
        <center><%= image_tag @posts.photo, class: 'photo' %></center>
      <% end %>
      
      <div class="post_body">
        <%= link_to @posts.user_name, user_path(@posts.user_id) %> <%= @posts.description %>
      </div>	
  <% if @posts.user == current_user %>
    <%= link_to 'Edit Post', edit_post_path(@posts.id) %>
    <%= link_to 'Delete Post', post_path(@posts.id), method: :delete %>
  <% end %>

<div class="post_comments">
      
        <% if user_signed_in? %>
          <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do |f| %>
            <%= f.input :description, label: 'Comment', placeholder: 'Add a comment...' %>
            <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
          <% end %>
        <% end %>
      </div>

app/views/relationships/follow_user.js.erb
$('#follow-button').attr('class', 'btn unfollow-button')
                   .text('Following')
                   .attr('href', "/<%= @user.user_id %>/unfollow_user")
                   .attr('id', 'unfollow-button');

app/views/relationships/unfollow_user.html.erb
<h1>Relationships#unfollow_user</h1>
<p>Find me in app/views/relationships/unfollow_user.html.erb</p>

app/views/relationships/unfollow_user.js.erb
$('#unfollow-button').text('Follow')
                     .attr('class', 'btn follow-button')
                     .attr('href', "/<%= @user.user_id %>/follow_user")
                     .attr('id', 'follow-button');

app/views/upvotes/create.js.erb
$('#likes_container_<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/users/show.html.erb
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="prof_header"> 
				<div class="row">
					<div class="col-xs-4">
			      		<%= image_tag @user.photo, class: 'prof_pic' %>
			    	</div>
					<div class="col-xs-8">
						<div class="user_header">
							<div class="row">
								<div class="col-xs-6">
						            <h1 class = "username"><%= @user.name %></h1>
						            <% if @user == current_user %>

						            	<div class="col-xs-6">
						            		<%= link_to 'EDIT PROFILE', edit_user_registration_path(@user), class: 'user_edit_button btn btn-default' %>
						            		<%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-cog", style="font-size:26px"></i><% end %>
										</div>
										
						            <% else %>
						            	
							            <% if current_user_is_following(current_user.id, @user.id) %>
							            	<%= link_to 'Following', unfollow_user_path(@user),remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
							            <% else %>
							            	<%= link_to 'Follow', follow_user_path(@user),remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
							            <% end %>
							            
			 				        <% end %>
						        </div>
								
			        		</div>  
			      		</div>
						<span class="count"><%= @user.posts.count %></span> posts
					</div>
				</div>

			</div>
		</div>
		<div class="panel-body">
			<div class="prof_post_box">
				<div class="row">
					<% @user.posts.each do |post| %>
						<div class="col-xs-3 marginalized">
							<%= link_to post_path(post.id) do %>
								<%= image_tag post.photo, class: 'prof_show' %>
							<% end %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>	